openapi: 3.0.1
info:
  title: monster-pit-fiend
  x-cortex-tag: monster-pit-fiend
  x-cortex-custom-metadata:
    alignment: chaotic-neutral
    type: monstrosity
    challenge_rating: 12
    legendary: false
    armor_class: 15
    hit_points: 247
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-pit-fiend
      alias: github-token-test
